//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS353.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLChannel
    {
        public int c_id { get; set; }
        public string c_name { get; set; }
        public Nullable<int> c_userID { get; set; }
        public string c_movieList { get; set; }
        public string c_seriesList { get; set; }
    
        public virtual TBLUser TBLUser { get; set; }
    }
}
