//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS353.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLComment
    {
        public int c_id { get; set; }
        public string c_text { get; set; }
        public string c_user { get; set; }
        public string c_movieName { get; set; }
        public string c_seasonName { get; set; }
        public string c_episodeName { get; set; }
    }
}
