//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS353.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEpisode
    {
        public int e_id { get; set; }
        public string e_name { get; set; }
        public Nullable<int> e_episodeNo { get; set; }
        public Nullable<int> e_seasonNo { get; set; }
        public Nullable<int> e_duration { get; set; }
        public string e_info { get; set; }
        public Nullable<int> e_seasonID { get; set; }
    
        public virtual TBLSeries TBLSeries { get; set; }
    }
}
