//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS353.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMessage
    {
        public int m_id { get; set; }
        public string m_from { get; set; }
        public string m_to { get; set; }
        public string m_subject { get; set; }
        public string m_text { get; set; }
        public Nullable<System.DateTime> m_time { get; set; }
    }
}
