//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS353.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMovie
    {
        public int m_id { get; set; }
        public string m_name { get; set; }
        public Nullable<int> m_duration { get; set; }
        public Nullable<double> m_imdbPoint { get; set; }
        public string m_info { get; set; }
        public Nullable<int> m_genreID { get; set; }
    
        public virtual TBLGenre TBLGenre { get; set; }
    }
}
