//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS353.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSeries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLSeries()
        {
            this.TBLEpisode = new HashSet<TBLEpisode>();
        }
    
        public int s_id { get; set; }
        public string s_name { get; set; }
        public Nullable<int> s_numberOfSeason { get; set; }
        public Nullable<int> s_numberOfEpisode { get; set; }
        public Nullable<double> s_imdbPoint { get; set; }
        public string s_info { get; set; }
        public Nullable<int> s_genreID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEpisode> TBLEpisode { get; set; }
        public virtual TBLGenre TBLGenre { get; set; }
    }
}
