//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS353.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLWishlist
    {
        public int w_id { get; set; }
        public string w_user { get; set; }
        public string w_name { get; set; }
    }
}
